import { Box } from "@chakra-ui/react";
import type { NextPage, NextPageContext } from "next";
import { getSession, useSession } from "next-auth/react";
import Head from "next/head";
import Auth from "../components/Auth/Auth";
import Chat from "../components/Chat/Chat";
import { Session } from 'next-auth';


const Home: NextPage = () => {
  const { data: session } = useSession(); 
  console.log('SESSION:', session);
  

  const reloadSession = () => {};
 
  return (
    <div>
      <Head>
        <title>iMessage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        {session?.user?.username ? <Chat /> : <Auth session={session} reloadSession={reloadSession} />}
      </Box>
      </div>
  );
};

export async function getServerSideProps(context: NextPageContext) {
  const session = await getSession(context);
  
  return {
    props: {
      session,
    },
  };
}

export default Home;
